version: '3.8'

services:
  app:
    build: .
    container_name: surveillance_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      # Volume pour la base de données, pour qu'elle persiste
      - surveillance_db:/app/surveillance.db
    environment:
      # Passer les clés d'API via les variables d'environnement
      # L'utilisateur devra créer un fichier .env à la racine
      - CAPTCHA_SOLVER_API_KEY=${CAPTCHA_SOLVER_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PROXIES_LIST=${PROXIES_LIST}

volumes:
  surveillance_db:
