services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: surveillance_backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - surveillance_db:/app/surveillance.db
    environment:
      - CAPTCHA_SOLVER_API_KEY=${CAPTCHA_SOLVER_API_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PROXIES_LIST=${PROXIES_LIST}
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: surveillance_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  scraper:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: surveillance_scraper
    command: node js/scraper_server.js
    ports:
      - "3001:3000" # Expose scraper on 3001 to avoid conflict with frontend dev server
    depends_on:
      - backend

  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  surveillance_db:
  redis_data:
